<?php
    // http://6d576a762ed0.ngrok.io/ussdsms/index.php
    include_once 'menu.php';
    include_once 'db.php';
    include_once 'user.php';

    // Read the variables sent via POST from our API
    $sessionId   = $_POST["sessionId"];//generated by the gateway to identify a session
    $serviceCode = trim($_POST["serviceCode"]);//dial code
    $phoneNumber = trim($_POST["phoneNumber"]);//mobile number of the user
    $text        = trim($_POST["text"]);//what the user enters

   
    $user = new User($phoneNumber);
    $db = new DBConnector();
    $pdo = $db->connectToDB();

    //Create object for Menu class 
    $menu = new Menu();
    $text = $menu->middleware($text, $user, $sessionId, $pdo);

    //user is registered and string is is empty
    if($text == "" && $user->isUserRegistered($pdo) == true){

        echo "CON " . $menu->mainMenuRegistered($user->readName($pdo));

    //user is unregistered and string is is empty
    }else if($text == "" && $user->isUserRegistered($pdo) == false){

         $menu->mainMenuUnRegistered();

    //user is unregistered and string is not empty
    }else if($user->isUserRegistered($pdo) == false){

        $textArray = explode("*", $text);
        switch($textArray[0]){
            case 1: 
                $menu->registerMenu($textArray, $phoneNumber,$pdo);
            break;
            default:
                echo "END Invalid choice. Please try again";
        }

    }else{
        //user is registered and string is not empty
        $textArray = explode("*", $text);
        switch($textArray[0]){
            case 1: //send money
                $menu->sendMoneyMenu($textArray,$user,$pdo,$sessionId);
            break;
            case 2: //withdraw money
                $menu->withdrawMoneyMenu($textArray,$user,$pdo);
            break;
            case 3://check balance
                $menu->checkBalanceMenu($textArray,$user,$pdo);
                break;
            default:
                $ussdLevel = count($textArray) - 1;
                $menu->persistInvalidEntry($sessionId,$user, $ussdLevel,$pdo);
                echo "CON Invalid menu\n" . $menu->mainMenuRegistered($user->readName($pdo));
        }
    }

/*
 *
 * */
